id: I57BD76B9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:58:41+00:00'
last_modified: '2022-06-07T12:02:11.333121+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3655
  title: འཇའ་ཚོན་པོད་དྲུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FE89:
      image_group_id: I1KG4164
      title: Volume 1 of gter chos/_'ja' tshon snying po
      total_pages: 608
      order: 1
      base_file: FE89.txt
    7A1E:
      image_group_id: I1KG4165
      title: Volume 2 of gter chos/_'ja' tshon snying po
      total_pages: 674
      order: 2
      base_file: 7A1E.txt
    F01C:
      image_group_id: I1KG4166
      title: Volume 3 of gter chos/_'ja' tshon snying po
      total_pages: 396
      order: 3
      base_file: F01C.txt
    '4948':
      image_group_id: I1KG4167
      title: Volume 4 of gter chos/_'ja' tshon snying po
      total_pages: 488
      order: 4
      base_file: 4948.txt
    DB6B:
      image_group_id: I1KG4168
      title: Volume 5 of gter chos/_'ja' tshon snying po
      total_pages: 712
      order: 5
      base_file: DB6B.txt
    '4806':
      image_group_id: I1KG4169
      title: Volume 6 of gter chos/_'ja' tshon snying po
      total_pages: 842
      order: 6
      base_file: 4806.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
